-- JUGOS NAYI: tablas normalizadas para ventas, plan y compras.
-- Uso interno: RLS desactivado.

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  sabor text not null,
  emoji text not null,
  tam text not null,
  qty integer not null default 0,
  precio numeric not null default 0,
  total numeric not null default 0,
  hora text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.plan_diario (
  id bigint generated by default as identity primary key,
  dia text not null,
  pg integer not null default 0,
  pp integer not null default 0,
  vg integer not null default 0,
  vp integer not null default 0,
  semana text not null
);

create table if not exists public.compras (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  cantidad numeric not null default 0,
  precio numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.ventas disable row level security;
alter table public.plan_diario disable row level security;
alter table public.compras disable row level security;
