-- Módulo ventas mayoristas (colmados / negocios)

create table if not exists public.mayoristas (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  telefono text not null default '',
  precio_grande numeric not null default 0,
  precio_pequeno numeric not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.ordenes_mayoristas (
  id bigint generated by default as identity primary key,
  mayorista_id bigint not null references public.mayoristas (id) on delete restrict,
  cantidad_grandes integer not null default 0,
  cantidad_pequenos integer not null default 0,
  precio_grande numeric not null default 0,
  precio_pequeno numeric not null default 0,
  total numeric not null default 0,
  notas text not null default '',
  estado text not null default 'pendiente',
  created_at timestamptz not null default now(),
  constraint ordenes_mayoristas_estado_chk check (estado in ('pendiente', 'entregado', 'cancelado'))
);

create index if not exists idx_ordenes_mayoristas_created on public.ordenes_mayoristas (created_at desc);
create index if not exists idx_ordenes_mayoristas_mayorista on public.ordenes_mayoristas (mayorista_id);

alter table public.mayoristas disable row level security;
alter table public.ordenes_mayoristas disable row level security;
